'use strict';
(function(){
const $=id=>document.getElementById(id);
const state={user:null,csrf:'',labs:[],tab:'labs',page:1,hasMore:false,userPage:1,userHasMore:false,sentPage:1,sentHasMore:false};
const statuses={CONFIRMED:'预约成功',CANCELLED:'已取消',WAITING:'候补中',WITHDRAWN:'已退出',PROMOTED:'已补位',SKIPPED:'已跳过'};
const showStatus=r=>r.status==='CANCELLED'&&r.cancel_reason==='NO_SHOW'?'已爽约':(statuses[r.status]||r.status);
const dateCN=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'});
const timeCN=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false});
const today=()=>dateCN.format(new Date());
const weekAgo=()=>dateCN.format(new Date(Date.now()-6*86400000));
const fmtTime=s=>timeCN.format(new Date(Number(s)*1000));
const fmtStamp=s=>dateCN.format(new Date(Number(s)*1000))+' '+fmtTime(s);
const slotRange=r=>fmtStamp(r.start_at)+' – '+fmtTime(r.end_at);
const sourceName=r=>r.source==='WAITLIST'?'候补补位':r.source==='DIRECT'?'直接预约':(r.source||'—');
const fmtUptime=v=>{const s=Number(v);if(!Number.isFinite(s))return '—';const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return (h>0?h+' 小时 ':'')+m+' 分';};
let kicked=false;
function kick(){if(kicked)return;kicked=true;location.replace('/');}
function gate(msg){if(kicked)return;kicked=true;note(msg,true);setTimeout(()=>location.replace('/'),900);}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function empty(target,text){target.replaceChildren(el('div',text,'empty'));}
function note(text,bad){const n=$('notice');n.textContent=text;n.classList.toggle('bad',!!bad);n.hidden=false;}
function setText(id,text){$(id).textContent=String(text);}
class ApiError extends Error{constructor(message,status,code,data){super(message);this.status=status||0;this.code=code||'NETWORK';this.data=data||null;}}
async function api(path,body){let r;try{r=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':state.csrf},body:body===undefined?undefined:JSON.stringify(body)});}catch(e){throw new ApiError('网络连接失败，请检查服务是否运行。');}let j;try{j=await r.json();}catch(e){throw new ApiError('服务返回了无法识别的响应。',r.status===503?503:0);}if(r.status===401){note('登录已过期，即将返回用户端。',true);kick();throw new ApiError('登录已过期。',401,'UNAUTHORIZED');}if(!r.ok||j.code!=='OK')throw new ApiError(j.message||'请求失败，请稍后重试。',r.status,j.code,j.data||null);return j.data;}
async function mutate(path,body,okMsg,button,onErr){if(button)button.disabled=true;try{const d=await api(path,Object.assign({},body,{request_id:crypto.randomUUID()}));note(typeof okMsg==='function'?okMsg(d):okMsg);return d;}catch(e){note(e.message+(e.status===503?' 数据库暂忙，可安全重试。':''),true);if(onErr)onErr(e);return null;}finally{if(button)button.disabled=false;}}
function action(text,fn,cls){const b=el('button',text,cls||'secondary');b.type='button';b.addEventListener('click',()=>fn(b));return b;}
function table(target,headers,rows){if(!rows.length){empty(target,'暂无数据');return;}const wrap=el('div',undefined,'table-wrap'),t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const body=el('tbody');for(const values of rows){const r=el('tr');for(const v of values){const cell=el('td');if(v instanceof Node)cell.append(v);else cell.textContent=v==null?'—':String(v);r.append(cell);}body.append(r);}t.append(body);wrap.append(t);target.replaceChildren(wrap);}
async function loadOverview(){const day=today();$('health-line').textContent='正在读取服务状态…';try{const[s,m,h]=await Promise.all([api('/api/admin/stats?start_date='+encodeURIComponent(day)+'&end_date='+encodeURIComponent(day)),api('/api/admin/metrics'),api('/api/health')]);const row=(s.stats||[]).find(x=>x.date===day)||{};setText('c-slots',row.slots??0);setText('c-confirmed',row.confirmed??0);setText('c-waiting',row.waiting??0);setText('c-checked',row.checked_in??0);const c=m.counters||{},total=Number(c.requests_total)||0;setText('c-rate',total?Math.round((Number(c.ok_2xx)||0)/total*1000)/10+'%':'—');$('c-rate-sub').textContent='5xx 错误 '+(c.err_5xx??0)+' · 503 数据库忙碌 '+(c.db_busy_503??0)+' · 登录 '+(c.logins??0)+' 次';$('health-line').textContent='服务版本 '+(h.version||'—')+' · 已连续运行 '+fmtUptime(h.uptime_s)+' · 日期与时间均为北京时间（UTC+8）';}catch(e){$('health-line').textContent='概览加载失败：'+e.message;}}
async function loadLabs(){try{const d=await api('/api/labs');state.labs=d.labs||[];renderLabs();renderLabOptions();}catch(e){empty($('admin-labs'),'实验室加载失败：'+e.message);}}
function renderLabs(){table($('admin-labs'),['名称','位置','说明','状态','操作'],state.labs.map(l=>[l.name,l.location||'—',l.description||'—',el('span',l.enabled?'启用':'停用','tag'+(l.enabled?'':' gray')),action('编辑',()=>{const f=$('lab-form');f.elements.id.value=l.id;f.elements.name.value=l.name||'';f.elements.location.value=l.location||'';f.elements.description.value=l.description||'';f.elements.enabled.checked=!!l.enabled;$('lab-form-title').textContent='编辑实验室：'+l.name;f.scrollIntoView({behavior:'smooth',block:'start'});})]));}
function fillLabSelect(sel){const old=sel.value;sel.replaceChildren();if(!state.labs.length){const o=el('option','暂无实验室，请先在「实验室管理」中新增');o.value='';sel.append(o);return;}state.labs.forEach(l=>{const o=el('option',l.name+(!l.enabled?'（已停用）':''));o.value=l.id;sel.append(o);});if(state.labs.some(l=>l.id===old))sel.value=old;}
function renderLabOptions(){fillLabSelect($('publish-lab'));fillLabSelect($('slots-lab'));}
async function loadRecords(){const p=state.page;const ea=$('events-action').value.trim(),eu=$('events-user').value.trim();empty($('admin-reservations'),'正在读取记录…');empty($('admin-waitlist'),'正在读取记录…');empty($('admin-events'),'正在读取记录…');try{const d=await api('/api/admin/records?date='+encodeURIComponent($('admin-date').value)+'&page='+p+'&page_size=20'+(ea?'&action='+encodeURIComponent(ea):'')+(eu?'&user='+encodeURIComponent(eu):''));table($('admin-reservations'),['ID','实验室','用户名','时段','状态','来源','签到时间'],(d.reservations||[]).map(r=>[r.id,r.lab_name,r.username,slotRange(r),showStatus(r),sourceName(r),r.checked_in_at?fmtStamp(r.checked_in_at):'—']));table($('admin-waitlist'),['ID','实验室','用户名','时段','状态','队列位置'],(d.waitlist||[]).map(r=>[r.id,r.lab_name,r.username,slotRange(r),statuses[r.status]||r.status,r.status==='WAITING'&&r.position?'第 '+r.position+' 位':'—']));table($('admin-events'),['时间','操作者','动作','对象','请求编号'],(d.events||[]).map(v=>[fmtStamp(v.created_at),v.actor,v.action,v.entity_id,v.request_id]));state.hasMore=!!d.has_more;$('admin-page').textContent='第 '+p+' 页'+(d.has_more?'（还有更多）':'');$('admin-prev').disabled=p<=1;$('admin-next').disabled=!d.has_more;}catch(e){empty($('admin-reservations'),'记录加载失败：'+e.message);empty($('admin-waitlist'),'请刷新重试');empty($('admin-events'),'请刷新重试');}}
async function loadUsers(){const p=state.userPage;empty($('admin-users'),'正在读取用户…');try{const q=$('users-q').value.trim();const d=await api('/api/admin/users?page='+p+'&page_size=20'+(q?'&q='+encodeURIComponent(q):''));const rows=(d.users||[]).map(u=>{const ns=u.no_show_count??0;return [u.id,u.username,u.role==='ADMIN'?'管理员':'用户',el('span',u.enabled?'启用':'停用','tag'+(u.enabled?'':' gray')),u.reservations??0,u.waitlisted??0,ns>=2?el('span','受限中','tag late'):ns,buildUserActions(u)];});table($('admin-users'),['ID','用户名','角色','状态','有效预约','候补中','近7天爽约','操作'],rows);state.userHasMore=!!d.has_more;$('users-page').textContent='第 '+p+' 页'+(d.has_more?'（还有更多）':'');$('users-prev').disabled=p<=1;$('users-next').disabled=!d.has_more;}catch(e){empty($('admin-users'),'用户加载失败：'+e.message);}}
function buildUserActions(u){const box=el('span',undefined,'actions');
 if(u.enabled)box.append(action('停用',b=>mutate('/api/admin/users/'+u.id+'/disable',{},'账号 '+u.username+' 已停用并下线。',b).then(ok=>{if(ok!==null)loadUsers();}),'secondary'));
 else box.append(action('启用',b=>mutate('/api/admin/users/'+u.id+'/enable',{},'账号 '+u.username+' 已启用。',b).then(ok=>{if(ok!==null)loadUsers();}),'secondary'));
 box.append(action('重置密码',b=>api('/api/admin/users/'+u.id+'/reset-password',{request_id:crypto.randomUUID()}).then(d=>{note('用户 '+u.username+' 的新密码：'+d.password+'（仅显示这一次，请立即复制）');loadUsers();}).catch(e=>note(e.message,true)),'secondary'));
 return box;}
async function loadSent(){const p=state.sentPage;empty($('admin-sent'),'正在读取通知历史…');try{const d=await api('/api/admin/notifications/sent?page='+p+'&page_size=20');table($('admin-sent'),['时间','类型','接收人','标题','正文','已读时间'],(d.sent||[]).map(n=>[fmtStamp(n.created_at),n.kind,n.username,n.title,n.body||'—',n.read_at?fmtStamp(n.read_at):'未读']));state.sentHasMore=!!d.has_more;$('sent-page').textContent='第 '+p+' 页 / 共 '+(d.total??'—')+' 条'+(d.has_more?'（还有更多）':'');$('sent-prev').disabled=p<=1;$('sent-next').disabled=!d.has_more;}catch(e){empty($('admin-sent'),'通知历史加载失败：'+e.message);}}
async function loadLogs(){const box=$('admin-logs');empty(box,'正在读取日志…');try{const lines=Number($('logs-lines').value)||100,level=$('logs-level').value;const d=await api('/api/admin/logs?lines='+lines+(level?'&level='+level:''));const list=d.lines||[];if(!list.length){empty(box,'日志为空。');return;}const pre=el('pre',list.join('\n'),'log-view');pre.id='log-pre';box.replaceChildren(pre,el('p','显示最近 '+list.length+' 行'+(d.truncated?'（日志文件较大，仅读取尾部）':'')+' · 文件大小 '+((d.file_size||0)/1024).toFixed(1)+' KB','muted'));}catch(e){empty(box,'日志加载失败：'+e.message);}}
/* -- r12 纯 SVG 柱状图（零依赖）：有效预约 / 已签到 双序列 -- */
function svgBarChart(rows){
 const NS='http://www.w3.org/2000/svg';
 const W=720,H=260,PL=42,PB=44,PT=16,PR=8;
 const max=Math.max(1,...rows.map(r=>Math.max(r[1],r[2])));
 const iw=(W-PL-PR)/rows.length,bw=Math.min(34,iw*0.55);
 const svg=document.createElementNS(NS,'svg');
 svg.setAttribute('viewBox','0 0 '+W+' '+H);svg.setAttribute('width','100%');svg.setAttribute('role','img');svg.setAttribute('aria-label','每日有效预约与已签到柱状图');
 const yv=v=>H-PB-(v/max)*(H-PB-PT);
 const line=(x1,y1,x2,y2,color)=>{const l=document.createElementNS(NS,'line');l.setAttribute('x1',x1);l.setAttribute('y1',y1);l.setAttribute('x2',x2);l.setAttribute('y2',y2);l.setAttribute('stroke',color);svg.append(l);};
 for(let g=0;g<=4;g++){const v=max*g/4,y=yv(v);line(PL,y,W-PR,y,'#edf0eb');const t=document.createElementNS(NS,'text');t.setAttribute('x',PL-6);t.setAttribute('y',y+4);t.setAttribute('text-anchor','end');t.setAttribute('font-size','10');t.setAttribute('fill','#6c7e75');t.textContent=Math.round(v*10)/10;svg.append(t);}
 rows.forEach((r,i)=>{
  const cx=PL+iw*i+iw/2;
  const b1=document.createElementNS(NS,'rect');b1.setAttribute('x',cx-bw-2);b1.setAttribute('y',yv(r[1]));b1.setAttribute('width',bw);b1.setAttribute('height',H-PB-yv(r[1]));b1.setAttribute('rx',3);b1.setAttribute('fill','#176d58');
  const t1=document.createElementNS(NS,'title');t1.textContent=r[0]+' 有效预约 '+r[1];b1.append(t1);svg.append(b1);
  const b2=document.createElementNS(NS,'rect');b2.setAttribute('x',cx+2);b2.setAttribute('y',yv(r[2]));b2.setAttribute('width',bw);b2.setAttribute('height',H-PB-yv(r[2]));b2.setAttribute('rx',3);b2.setAttribute('fill','#d6a24f');
  const t2=document.createElementNS(NS,'title');t2.textContent=r[0]+' 已签到 '+r[2];b2.append(t2);svg.append(b2);
  const lab=document.createElementNS(NS,'text');lab.setAttribute('x',cx);lab.setAttribute('y',H-PB+16);lab.setAttribute('text-anchor','middle');lab.setAttribute('font-size','10');lab.setAttribute('fill','#6c7e75');lab.textContent=r[0].slice(5);svg.append(lab);
 });
 const lg1=document.createElementNS(NS,'rect');lg1.setAttribute('x',PL);lg1.setAttribute('y',4);lg1.setAttribute('width',12);lg1.setAttribute('height',12);lg1.setAttribute('fill','#176d58');svg.append(lg1);
 const lt1=document.createElementNS(NS,'text');lt1.setAttribute('x',PL+16);lt1.setAttribute('y',14);lt1.setAttribute('font-size','11');lt1.setAttribute('fill','#18322d');lt1.textContent='有效预约';svg.append(lt1);
 const lg2=document.createElementNS(NS,'rect');lg2.setAttribute('x',PL+78);lg2.setAttribute('y',4);lg2.setAttribute('width',12);lg2.setAttribute('height',12);lg2.setAttribute('fill','#d6a24f');svg.append(lg2);
 const lt2=document.createElementNS(NS,'text');lt2.setAttribute('x',PL+94);lt2.setAttribute('y',14);lt2.setAttribute('font-size','11');lt2.setAttribute('fill','#18322d');lt2.textContent='已签到';svg.append(lt2);
 return svg;
}
async function loadStats(){const start=$('stats-start').value,end=$('stats-end').value;if(!start||!end){note('请先选择统计的起止日期。',true);return;}empty($('admin-stats'),'正在读取统计…');const chartBox=$('stats-chart');chartBox.replaceChildren();try{const d=await api('/api/admin/stats?start_date='+encodeURIComponent(start)+'&end_date='+encodeURIComponent(end));const list=d.stats||[];if(!list.length){empty($('admin-stats'),'所选日期范围内暂无统计数据。');return;}const rows=list.map(r=>[r.date,r.slots,r.confirmed,r.cancelled,r.no_show,r.checked_in,r.waiting]);const t=d.totals||{};rows.push(['合计',t.slots??'—',t.confirmed??'—',t.cancelled??'—',t.no_show??'—',t.checked_in??'—',t.waiting??'—']);table($('admin-stats'),['日期','开放场次','有效预约','已取消','已爽约','已签到','候补人数'],rows);if(list.length)chartBox.append(el('h3','预约趋势'),svgBarChart(list.map(r=>[r.date,r.confirmed,r.checked_in])));}catch(e){empty($('admin-stats'),'统计加载失败：'+e.message);}}
async function exportStats(){const start=$('stats-start').value,end=$('stats-end').value;if(!start||!end){note('请先选择统计的起止日期。',true);return;}const b=$('export-stats');b.disabled=true;try{const d=await api('/api/admin/stats/export?start_date='+encodeURIComponent(start)+'&end_date='+encodeURIComponent(end));const blob=new Blob([d.content],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=d.filename||'stats.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);note('统计报表已导出：'+(d.filename||'stats.csv'));}catch(e){note(e.message,true);}finally{b.disabled=false;}}
async function loadMetrics(){const box=$('admin-metrics');empty(box,'正在读取指标…');try{const d=await api('/api/admin/metrics');const c=d.counters||{},l=d.latency_ms||{},cnt=Number(l.count)||0;const wrap=el('div');wrap.append(el('h3','请求计数'));const ct=el('div');table(ct,['指标','数值'],[['请求总数',c.requests_total??0],['成功 2xx',c.ok_2xx??0],['客户端错误 4xx',c.err_4xx??0],['服务端错误 5xx',c.err_5xx??0],['其中 503 数据库忙碌',c.db_busy_503??0],['登录成功次数',c.logins??0]]);wrap.append(ct);const avg=cnt?Math.round((Number(l.sum)||0)/cnt*100)/100:0,mx=Math.round((Number(l.max)||0)*100)/100;wrap.append(el('h3','延迟分布（毫秒 · 样本 '+cnt+' · 平均 '+avg+' · 最大 '+mx+'）'));const bounds=['≤1','≤2','≤5','≤10','≤20','≤50','≤100','≤200','≤500','≤1000','≤2000','>2000'];const lt=el('div');table(lt,['区间 (ms)','请求数','占比'],(l.buckets||[]).map((v,i)=>[bounds[i]||'桶'+i,v,cnt?Math.round(v/cnt*1000)/10+'%':'—']));wrap.append(lt);box.replaceChildren(wrap);}catch(e){empty(box,'指标加载失败：'+e.message);}}
function renderSlots(list){table($('admin-slots'),['时段','容量','已确认','候补','状态','操作'],list.map(s=>[fmtTime(s.start_at)+' – '+fmtTime(s.end_at),s.capacity,s.confirmed_count??0,s.waiting_count??0,el('span',s.enabled?'启用':'停用','tag'+(s.enabled?'':' gray')),action('修改',()=>editSlot(s))]));}
function editSlot(s){const f=$('slot-form');f.elements.id.value=s.id;f.elements.capacity.value=s.capacity;f.elements.enabled.checked=!!s.enabled;f.elements.capacity.style.borderColor='';$('slot-form-title').textContent='修改场次：'+fmtTime(s.start_at)+' – '+fmtTime(s.end_at);f.scrollIntoView({behavior:'smooth',block:'start'});}
function resetSlotForm(){const f=$('slot-form');f.reset();f.elements.id.value='';f.elements.capacity.style.borderColor='';$('slot-form-title').textContent='修改场次';}
async function loadSlots(){const lab=$('slots-lab').value,day=$('slots-date').value||today();if(!lab){empty($('admin-slots'),'暂无实验室，请先在「实验室管理」中新增。');return;}empty($('admin-slots'),'正在读取场次…');try{const d=await api('/api/slots?lab_id='+encodeURIComponent(lab)+'&date='+encodeURIComponent(day));renderSlots(d.slots||[]);}catch(e){empty($('admin-slots'),'场次加载失败：'+e.message);}}
async function switchTab(tab){state.tab=tab;for(const t of ['labs','publish','slots','records','users','stats','metrics','notify','sent','logs'])$(t+'-view').hidden=t!==tab;document.querySelectorAll('#tabs [data-tab]').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});await refreshCurrent();}
async function refreshCurrent(){try{if(state.tab==='labs'||state.tab==='publish')await loadLabs();if(state.tab==='slots'){if(!state.labs.length)await loadLabs();await loadSlots();}if(state.tab==='records')await loadRecords();if(state.tab==='users')await loadUsers();if(state.tab==='stats')await loadStats();if(state.tab==='metrics')await loadMetrics();if(state.tab==='sent')await loadSent();if(state.tab==='logs')await loadLogs();}catch(e){note(e.message,true);}}
document.querySelectorAll('#tabs [data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
$('logout').addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{await api('/api/logout',{request_id:crypto.randomUUID()});location.href='/';}catch(err){note(err.message,true);b.disabled=false;}});
$('refresh-overview').addEventListener('click',()=>loadOverview());
$('refresh-labs').addEventListener('click',()=>loadLabs());
$('reset-lab').addEventListener('click',()=>{const f=$('lab-form');f.reset();f.elements.id.value='';$('lab-form-title').textContent='新增实验室';});
$('lab-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value,b=f.querySelector('button[type="submit"]');const body={name:f.elements.name.value.trim(),location:f.elements.location.value.trim(),description:f.elements.description.value.trim()};if(id)body.enabled=f.elements.enabled.checked;const d=await mutate(id?'/api/admin/labs/'+id+'/update':'/api/admin/labs',body,'实验室信息已保存。',b);if(d!==null){$('reset-lab').click();await loadLabs();}});
$('publish-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button[type="submit"]');const start=f.elements.start_date.value,end=f.elements.end_date.value,capacity=Math.floor(Number(f.elements.capacity.value));const days=(Date.parse(end+'T00:00:00Z')-Date.parse(start+'T00:00:00Z'))/86400000+1;if(!f.elements.lab_id.value){note('请先在「实验室管理」中新增实验室。',true);return;}if(!start||!end||!Number.isFinite(days)||days<1||days>14){note('请选择按先后排列、总计不超过 14 天的日期范围。',true);return;}if(!Number.isFinite(capacity)||capacity<1||capacity>200){note('容量需为 1..200 的整数。',true);return;}const d=await mutate('/api/admin/slots/publish',{lab_id:String(f.elements.lab_id.value),start_date:start,end_date:end,capacity},r=>'发布完成，已创建 '+r.created+' 个场次。',b);if(d!==null)await loadOverview();});
$('admin-date').addEventListener('change',()=>{state.page=1;loadRecords();});
$('admin-prev').addEventListener('click',()=>{if(state.page>1){state.page--;loadRecords();}});
$('admin-next').addEventListener('click',()=>{if(!state.hasMore)return;state.page++;loadRecords();});
$('refresh-records').addEventListener('click',()=>{state.page=1;loadRecords();});
$('events-action').addEventListener('change',()=>{state.page=1;loadRecords();});
$('events-user').addEventListener('change',()=>{state.page=1;loadRecords();});
$('refresh-users').addEventListener('click',()=>{state.userPage=1;loadUsers();});
$('users-query').addEventListener('click',()=>{state.userPage=1;loadUsers();});
$('users-q').addEventListener('change',()=>{state.userPage=1;loadUsers();});
$('users-prev').addEventListener('click',()=>{if(state.userPage>1){state.userPage--;loadUsers();}});
$('users-next').addEventListener('click',()=>{if(state.userHasMore){state.userPage++;loadUsers();}});
$('refresh-sent').addEventListener('click',()=>{state.sentPage=1;loadSent();});
$('refresh-logs').addEventListener('click',()=>loadLogs());
$('logs-lines').addEventListener('change',()=>loadLogs());
$('logs-level').addEventListener('change',()=>loadLogs());
$('sent-prev').addEventListener('click',()=>{if(state.sentPage>1){state.sentPage--;loadSent();}});
$('sent-next').addEventListener('click',()=>{if(state.sentHasMore){state.sentPage++;loadSent();}});
$('refresh-stats').addEventListener('click',()=>loadStats());
$('export-stats').addEventListener('click',()=>exportStats());
$('refresh-metrics').addEventListener('click',()=>loadMetrics());
$('slots-query').addEventListener('click',()=>loadSlots());
$('refresh-slots').addEventListener('click',()=>loadSlots());
$('slots-date').addEventListener('change',()=>loadSlots());
$('reset-slot').addEventListener('click',()=>resetSlotForm());
$('slot-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button[type="submit"]');const id=f.elements.id.value,cap=Math.floor(Number(f.elements.capacity.value));f.elements.capacity.style.borderColor='';if(!id){note('请先在列表中点击「修改」选择场次。',true);return;}if(!Number.isFinite(cap)||cap<1||cap>200){note('容量需为 1..200 的整数。',true);return;}const d=await mutate('/api/admin/slots/'+encodeURIComponent(id)+'/update',{capacity:cap,enabled:f.elements.enabled.checked},'场次已更新。',b,err=>{if(err.status===409)f.elements.capacity.style.borderColor='#c0392b';});if(d!==null){resetSlotForm();await loadSlots();}});
$('slot-form').elements.capacity.addEventListener('input',()=>{$('slot-form').elements.capacity.style.borderColor='';});
document.querySelectorAll('#notify-form [name="target"]').forEach(r=>r.addEventListener('change',()=>{$('notify-user-wrap').hidden=$('notify-form').elements.target.value!=='user';}));
$('notify-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button[type="submit"]');const all=f.elements.target.value==='all',title=f.elements.title.value.trim(),body=f.elements.body.value.trim(),username=f.elements.username.value.trim();if(!title){note('请填写通知标题。',true);return;}if(!all&&!username){note('请填写要通知的用户名。',true);return;}const d=await mutate('/api/admin/notifications',all?{all:true,title,body}:{username,title,body},r=>'通知已发送给 '+(r.sent??0)+' 位用户。',b);if(d!==null){f.reset();$('notify-user-wrap').hidden=true;}});
$('admin-date').value=today();$('publish-form').elements.start_date.value=today();$('publish-form').elements.end_date.value=today();$('stats-start').value=weekAgo();$('stats-end').value=today();$('slots-date').value=today();
(async()=>{try{const r=await fetch('/api/me',{credentials:'same-origin'});if(r.status===401)return gate('请先使用管理员账号登录，即将返回用户端。');const j=await r.json().catch(()=>null);if(!j||j.code!=='OK'||!j.data||!j.data.user)return gate('身份验证失败，即将返回用户端。');if(j.data.user.role!=='ADMIN')return gate('需要管理员权限，即将返回用户端。');state.user=j.data.user;state.csrf=j.data.csrf_token||'';}catch(e){return gate('网络连接失败，请检查服务是否运行，即将返回用户端。');}$('identity').textContent=state.user.username+' · 管理员';$('gate').hidden=true;$('topbar').hidden=false;$('app').hidden=false;await loadOverview();await switchTab('labs');})();
})();
