'use strict';
const $ = id => document.getElementById(id);
const state = {user:null,csrf:'',labs:[],tab:'book',pending:null,busy:false,query:0};
const statuses = {CONFIRMED:'预约成功',CANCELLED:'已取消',WAITING:'候补中',WITHDRAWN:'已退出',PROMOTED:'已补位',SKIPPED:'已跳过'};
const dateCN = new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'});
const timeCN = new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false});
const today = () => dateCN.format(new Date());
const stamp = t => dateCN.format(new Date(Number(t)*1000))+' '+timeCN.format(new Date(Number(t)*1000));
const time = t => timeCN.format(new Date(Number(t)*1000));
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function empty(target,text){target.replaceChildren(el('div',text,'empty'));}
function note(text,bad=false){$('notice').textContent=text;$('notice').classList.toggle('bad',bad);$('notice').hidden=false;}
class ApiError extends Error{constructor(message,status=0,code='NETWORK',data=null){super(message);this.status=status;this.code=code;this.data=data;}}
async function api(path,body){let r;try{r=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':state.csrf},body:body===undefined?undefined:JSON.stringify(body)});}catch(e){throw new ApiError('网络连接失败，请检查服务是否运行。');}let j;try{j=await r.json();}catch(e){throw new ApiError('服务返回了无法识别的响应。',r.status===503?503:0);}if(r.status===401&&state.user){showLogin();$('login-error').textContent='登录已过期，请重新登录；未确认操作的请求编号已保留。';}if(!r.ok||j.code!=='OK')throw new ApiError(j.message||'请求失败，请稍后重试。',r.status,j.code,j.data||null);return j.data;}
function showLogin(){state.user=null;state.csrf='';state.pending=null;$('retry-area').hidden=true;$('app-view').hidden=true;$('account').hidden=true;$('login-view').hidden=false;}
function restorePending(){try{const p=JSON.parse(sessionStorage.getItem('lab-pending')||'null');if(p&&p.user===state.user.id&&typeof p.path==='string'&&p.path.startsWith('/api/')&&p.body&&typeof p.body.request_id==='string')state.pending=p;else state.pending=null;}catch(e){state.pending=null;}$('retry-area').hidden=!state.pending;}
function rememberPending(){try{if(state.pending)sessionStorage.setItem('lab-pending',JSON.stringify(state.pending));else sessionStorage.removeItem('lab-pending');}catch(e){/* In-memory retry remains available. */}$('retry-area').hidden=!state.pending;}
function lock(on){state.busy=on;document.querySelectorAll('button').forEach(b=>{if(on){b.dataset.wasDisabled=b.disabled?'1':'0';b.disabled=true;}else{b.disabled=b.dataset.wasDisabled==='1';delete b.dataset.wasDisabled;}});}
async function mutation(path,body,message,button,retry=false,onError=null){if(state.busy)return;if(state.pending&&!retry){note('请先重试并确认上次操作的结果，再执行新的操作。',true);return;}if(!retry){state.pending={user:state.user.id,path,body:{...body,request_id:crypto.randomUUID()},message};rememberPending();}const p=state.pending;if(!p)return;lock(true);let refresh=false,caught=null;try{await api(p.path,p.body);note(p.message);state.pending=null;rememberPending();refresh=true;}catch(e){caught=e;note(e.message+(e.status===503?' 数据库暂忙，可以安全重试。':''),true);if(e.status!==0&&e.status!==503&&e.status!==500&&e.status!==401){state.pending=null;rememberPending();refresh=true;}}finally{lock(false);}if(refresh)await refreshCurrent();if(caught&&onError)try{onError(caught);}catch(_){/* 展示回调异常不影响主流程 */}}
async function simplePost(path,body,message){if(state.busy)return;lock(true);try{const d=await api(path,body);note(typeof message==='function'?message(d):message);return d;}catch(e){note(e.message,true);return null;}finally{lock(false);}}
async function enter(d){state.user=d.user;state.csrf=d.csrf_token;$('identity').textContent=d.user.username+' · '+(d.user.role==='ADMIN'?'管理员':'普通用户');$('login-view').hidden=true;$('app-view').hidden=false;$('account').hidden=false;$('admin-tab').hidden=d.user.role!=='ADMIN';restorePending();await loadLabs();await switchTab('book');}
async function loadLabs(){const d=await api('/api/labs');state.labs=d.labs||[];const old=$('lab-select').value;for(const id of ['lab-select','publish-lab']){const select=$(id);select.replaceChildren();state.labs.forEach(l=>{const o=el('option',l.name+(!l.enabled?'（已停用）':''));o.value=l.id;select.append(o);});}if(state.labs.some(l=>l.id===old))$('lab-select').value=old;renderAdminLabs();}
async function switchTab(tab){state.tab=tab;for(const t of ['book','mine','admin'])$(t+'-view').hidden=t!==tab;document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});await refreshCurrent();}
async function refreshCurrent(){try{if(state.tab==='book')await loadSlots();if(state.tab==='mine')await loadRecords(false);if(state.tab==='admin'){await loadLabs();await loadRecords(true);await loadStats();}}catch(e){note(e.message,true);}}
function action(text,fn,cls='secondary'){const b=el('button',text,cls);b.type='button';b.addEventListener('click',()=>fn(b));return b;}
function renderAlternatives(list){const box=$('alternatives');box.hidden=false;box.replaceChildren(el('h3','该场次已满，可预约以下近期时段'),el('p','同一实验室、所选场次之后 7 天内、按时间排序的空闲场次，最多 3 个；提交时会重新校验。','muted'));if(!list.length){box.append(el('div','当前 7 天内暂无其他空闲时段，可选择加入候补。','empty'));return;}const grid=el('div',undefined,'slot-grid');for(const s of list){const card=el('article',undefined,'slot');card.append(el('span','可预约','tag'),el('div',stamp(s.start_at)+' – '+time(s.end_at),'slot-time'),el('p','候补 0 人','muted'));card.append(action('立即预约',b=>mutation('/api/reservations',{slot_id:s.id},'预约成功，可在我的记录查看。',b,false,e=>{if(e.code==='SLOT_FULL'&&e.data&&Array.isArray(e.data.alternatives))renderAlternatives(e.data.alternatives);else if(e.code==='SLOT_FULL')renderAlternatives([]);}),'primary'));grid.append(card);}box.append(grid);}
async function loadSlots(){const target=$('slots');const alts=$('alternatives');alts.hidden=true;alts.replaceChildren();const token=++state.query;const lab=state.labs.find(l=>l.id===$('lab-select').value);if(!lab){empty(target,'暂无实验室，请联系管理员。');return;}$('lab-name').textContent=lab.name;$('lab-description').textContent=[lab.location,lab.description].filter(Boolean).join(' · ');if(!$('book-date').value){empty(target,'请选择有效日期。');return;}empty(target,'正在读取开放时段…');try{const d=await api('/api/slots?lab_id='+encodeURIComponent(lab.id)+'&date='+encodeURIComponent($('book-date').value));if(token!==state.query)return;target.replaceChildren();if(!d.slots.length){empty(target,'当日暂无开放场次，请选择其他日期或联系管理员发布。');return;}for(const s of d.slots){const card=el('article',undefined,'slot');const started=Number(s.start_at)*1000<=Date.now();const disabled=!s.enabled||!s.lab_enabled||started;let label=started?'已开始':!s.enabled||!s.lab_enabled?'暂不可预约':s.my_reservation_id?'我的预约':s.my_waitlist_id?'我的候补':s.occupied?'已占用':'可预约';card.append(el('span',label,'tag'+(disabled?' gray':s.occupied?' busy':'')),el('div',time(s.start_at)+' – '+time(s.end_at),'slot-time'),el('p','候补 '+s.waiting_count+' 人','muted'));if(!started&&s.my_reservation_id)card.append(action('取消预约',b=>mutation('/api/reservations/'+s.my_reservation_id+'/cancel',{},'预约已取消，如有候补已自动处理。',b)));else if(!started&&s.my_waitlist_id)card.append(action('退出候补',b=>mutation('/api/waitlist/'+s.my_waitlist_id+'/withdraw',{},'已退出候补。',b)));else if(!disabled)card.append(action(s.occupied?'加入候补':'立即预约',b=>mutation(s.occupied?'/api/waitlist':'/api/reservations',{slot_id:s.id},s.occupied?'已加入候补，可在我的记录查看顺序。':'预约成功，可在我的记录查看。',b,false,s.occupied?null:e=>{if(e.code==='SLOT_FULL'&&e.data&&Array.isArray(e.data.alternatives))renderAlternatives(e.data.alternatives);}),s.occupied?'secondary':'primary'));else card.append(el('p','当前场次不接受新申请','muted'));target.append(card);}}catch(e){if(token===state.query)empty(target,'时段加载失败：'+e.message);}}
function table(target,headers,rows){if(!rows.length){empty(target,'暂无记录');return;}const wrap=el('div',undefined,'table-wrap'),t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const body=el('tbody');for(const values of rows){const r=el('tr');for(const v of values){const cell=el('td');if(v instanceof Node)cell.append(v);else cell.textContent=v==null?'—':String(v);r.append(cell);}body.append(r);}t.append(body);wrap.append(t);target.replaceChildren(wrap);}
async function loadRecords(admin){const prefix=admin?'admin-':'';empty($(prefix+'reservations'),'正在读取记录…');empty($(prefix+'waitlist'),'正在读取记录…');try{const d=await api(admin?'/api/admin/records?date='+encodeURIComponent($('admin-date').value):'/api/me/records');const cols=admin?['用户','实验室','时间','状态','来源']:['实验室','时间','状态','来源','操作'];const rows=(d.reservations||[]).map(r=>{const fields=[r.lab_name,stamp(r.start_at),statuses[r.status]||r.status,r.source==='WAITLIST'?'候补补位':r.source==='DIRECT'?'直接预约':r.source];if(admin)return[r.username,...fields];fields.push(r.status==='CONFIRMED'&&Number(r.start_at)*1000>Date.now()?action('取消预约',b=>mutation('/api/reservations/'+r.id+'/cancel',{},'预约已取消。',b)):'—');return fields;});table($(prefix+'reservations'),cols,rows);table($(prefix+'waitlist'),admin?['用户','实验室','时间','状态','顺序']:['实验室','时间','状态','顺序','操作'],(d.waitlist||[]).map(r=>{const fields=[r.lab_name,stamp(r.start_at),statuses[r.status]||r.status,r.status==='WAITING'&&r.position?'第 '+r.position+' 位':'—'];if(admin)return[r.username,...fields];fields.push(r.status==='WAITING'&&Number(r.start_at)*1000>Date.now()?action('退出候补',b=>mutation('/api/waitlist/'+r.id+'/withdraw',{},'已退出候补。',b)):'—');return fields;}));if(admin)table($('admin-events'),['操作者','操作','对象编号','时间','请求编号'],(d.events||[]).map(e=>[e.actor,e.action,e.entity_id,stamp(e.created_at),e.request_id]));}catch(e){empty($(prefix+'reservations'),'记录加载失败：'+e.message);empty($(prefix+'waitlist'),'请刷新重试');if(admin)empty($('admin-events'),'请刷新重试');}}
function renderAdminLabs(){table($('admin-labs'),['名称','位置','状态','操作'],state.labs.map(l=>[l.name,l.location,l.enabled?'启用':'停用',action('编辑',()=>{const f=$('lab-form');for(const key of ['id','name','location','description'])f.elements[key].value=l[key]||'';f.elements.enabled.checked=!!l.enabled;$('lab-form-title').textContent='编辑实验室';f.scrollIntoView({behavior:'smooth',block:'start'});})]));}
async function loadStats(){const start=$('stats-start').value,end=$('stats-end').value;if(!start||!end)return;try{const d=await api('/api/admin/stats?start_date='+encodeURIComponent(start)+'&end_date='+encodeURIComponent(end));const cols=['日期','开放场次','有效预约','已取消','候补人数'];const rows=(d.stats||[]).map(r=>[r.date,r.slots,r.confirmed,r.cancelled,r.waiting]);const t=d.totals||{};rows.push(['合计',t.slots??'—',t.confirmed??'—',t.cancelled??'—',t.waiting??'—']);table($('admin-stats'),cols,rows);}catch(e){empty($('admin-stats'),'统计加载失败：'+e.message);}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;$('login-error').textContent='';try{const d=await api('/api/login',{username:f.elements.username.value,password:f.elements.password.value});f.elements.password.value='';await enter(d);}catch(err){$('login-error').textContent=err.message;}finally{b.disabled=false;}});
$('logout').addEventListener('click',async()=>{try{await api('/api/logout',{});showLogin();}catch(e){note(e.message,true);}});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
$('retry').addEventListener('click',()=>mutation(null,null,null,null,true));
$('lab-select').addEventListener('change',loadSlots);$('book-date').addEventListener('change',loadSlots);$('refresh-slots').addEventListener('click',loadSlots);$('refresh-mine').addEventListener('click',()=>loadRecords(false));$('refresh-admin').addEventListener('click',()=>loadRecords(true));$('refresh-stats').addEventListener('click',loadStats);
$('reset-lab').addEventListener('click',()=>{$('lab-form').reset();$('lab-form').elements.id.value='';$('lab-form-title').textContent='新增实验室';});
$('lab-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value;const body={name:f.elements.name.value.trim(),location:f.elements.location.value.trim(),description:f.elements.description.value.trim()};if(id)body.enabled=f.elements.enabled.checked;const d=await simplePost(id?'/api/admin/labs/'+id+'/update':'/api/admin/labs',body,'实验室信息已保存。');if(d!==null){$('reset-lab').click();try{await loadLabs();}catch(err){note(err.message,true);}}});
$('publish-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,start=f.elements.start_date.value,end=f.elements.end_date.value,days=(Date.parse(end+'T00:00:00Z')-Date.parse(start+'T00:00:00Z'))/86400000+1;if(!Number.isFinite(days)||days<1||days>14){note('请选择按先后排列、总计不超过 14 天的日期范围。',true);return;}await simplePost('/api/admin/slots/publish',{lab_id:f.elements.lab_id.value,start_date:start,end_date:end},d=>'发布完成，新建 '+d.created+' 个场次。');});
$('book-date').value=today();$('admin-date').value=today();$('stats-start').value=today();$('stats-end').value=today();$('publish-form').elements.start_date.value=today();$('publish-form').elements.end_date.value=today();
(async()=>{try{await enter(await api('/api/me'));}catch(e){showLogin();if(e.status!==401)$('login-error').textContent=e.message;}})();
